package com.hack.TransmissionLineService;

public enum Action {
	NO_PENDING_ACTION, APPLY_CONSTRAINT, ACCEPT_DISPATCH, SEND_DISPATCH, UPDATE_CONSTRAINT, RECOMMEND_CONSTRAINT, GET_POOL_PRICE,
	POST_POOL_PRICE;
}
